---
- name: Uncordon node
  command: >-
    {{ bin_dir }}/kubectl
    --kubeconfig /home/auser/.kube/config
    uncordon
    {{ kube_override_hostname|default(inventory_hostname) }}
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: Wait for node to uncordon
  command: >-
    {{ bin_dir }}/kubectl
    --kubeconfig /home/auser/.kube/config
    get
    node
    {{ kube_override_hostname|default(inventory_hostname) }}
    -o json
  register: wait_for_uncordon
  retries: 10
  delay: 10
  delegate_to: "{{ groups['kube-master'][0] }}"
  changed_when: false
  until: not (kubectl_get_node['stdout'] | from_json).spec.unschedulable is defined
