# Authoritative Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: powerdns
  namespace: dns-test
spec:
  selector:
    matchLabels:
      app: powerdns
  template:
    metadata:
      labels:
        app: powerdns
    spec:
      containers:
      - name: pdns-server
        image:  powerdns/pdns-auth-47:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: auth-dns
          containerPort: 53
          protocol: UDP
        - name: api
          containerPort: 8081
          protocol: TCP
        env:
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASS
          value: password
        - name: MYSQL_PORT
          value: '3306'
        - name: MYSQL_HOST
          value: pdns-mysql
      - name: pdns-recursor
        image: powerdns/pdns-recursor-47:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: recursor-dns
          containerPort: 53
          protocol: UDP
        env:
        - name: blah
          value: '1234'
      - name: pdns-mysql
        image: mariadb:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - name: mysql
            containerPort: 3306
            protocol: TCP
        env:
        - name: MARIADB_USER
          value: root
        - name: MARIADB_PASS
          value: password
        - name: MARIADB_ROOT_PASSWORD
          value: password
      - name: pdns-admin
        image: ngoduykhanh/powerdns-admin:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - name: admin-portal
            containerPort: 80
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: pdns-server-dns
  namespace: dns-test
spec:
  selector:
    app: powerdns
  type: ClusterIP
  ports:
  - port: 53
    targetPort: 53
    protocol: UDP
    name: dns-udp
---
apiVersion: v1
kind: Service
metadata:
  name: pdns-server-api
  namespace: dns-test
spec:
  selector:
    app: powerdns
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: pdns-api


