---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
            #      volumes:
            #        - name: pihole-etc
            #          persistentVolumeClaim:
            #            claimName: pihole-etc
            #        - name: pihole-dnsmasq
            #          persistentVolumeClaim:
            #            claimName: pihole-dnsmasq
      containers:
      - name: pihole
        image: pihole/pihole:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - name: udp
          containerPort: 53
          protocol: UDP
        - name: tcp
          containerPort: 53
          protocol: TCP
        - name: web
          containerPort: 80
          protocol: TCP
        env:
          - name: TZ
            value: 'America/New York'
          - name: PIHOLE_DNS_
            value: 127.0.0.1;1.1.1.1
          - name: ADMIN_EMAIL
            value: ekauba@kaubalegacy.com
          - name: WEBTHEME
            value: default-dark
          - name: WEBPASSWORD
            value: "password"
            #        volumeMounts:
            #          - name: pihole-etc
            #            mountPath: /etc/pihole/
            #          - name: pihole-dnsmasq
            #            mountPath: /etc/dnsmasq.d/
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: dns
spec:
  selector:
    app: pihole
  type: LoadBalancer
  loadBalancerIP: 192.168.57.150
  externalTrafficPolicy: Local
  ports:
  - port: 53
    targetPort: 53
    protocol: UDP
    name: dns-udp
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: dns
spec:
  selector:
    app: pihole
  type: LoadBalancer
  loadBalancerIP: 192.168.57.150
  externalTrafficPolicy: Local
  ports:
  - port: 53
    targetPort: 53
    protocol: TCP
    name: dns-tcp
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dashboard
spec:
  selector:
    app: pihole
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: web
    #---
    #apiVersion: traefik.containo.us/v1alpha1
    #kind: IngressRoute
    #metadata:
    #  name: pihole-dashboard
    #spec:
    #  entryPoints:
    #    - web
    #  routes:
    #    - match: Host(`pihole.kaubalegacy.com`)
    #      kind: Rule
    #      services:
    #        - name: pihole-dashboard
    #          port: 80

