- hosts:
    - all
  become: true

  tasks:
    - name: Kubeadm Reset
      command: >-
        /usr/bin/kubeadm
        reset
        --force
      
    - name: Remove CNI configuration
      command: rm -r /etc/cni/net.d
      ignore_errors: true

    - name: Remove .kube cache
      command: rm -r /home/auser/.kube/cache
      ignore_errors: true

    - name: Reboot
      command: reboot