---
- hosts:
    - kube-master
    - kube-node
  become: true
  become_user: root
  serial: 1
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"

  roles:
    - k8s-rolling-update
  vars: 
    - bin_dir: /usr/local/bin
