apiVersion: v1
kind: Service
metadata:
    name: mysql-server
    namespace: dns-dev
spec:
    selector:
        app: mysql-server
    ports:
    - name: mysql-srv
      protocol: UDP
      port: 3306
      targetPort: 3306