apiVersion: apps/v1
kind: Deployment
metadata:
  name: powerdns-recursor
  namespace: dns-dev
spec:
  selector:
    matchLabels:
      app: powerdns-recursor
  template:
    metadata:
      labels:
        app: powerdns-recursor
    spec:
      containers:
      - name: pdns-recursor
        image: powerdns/pdns-recursor-master:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: recursor-dns
          containerPort: 9053
          protocol: UDP
<<<<<<< HEAD
        {{ $list := list .Values.recursor.args }}
        args: {{- range $list }}
=======
        {{- range $arg := .Values.recursor.args }}
        args: {{ $arg | quote}}
        {{- end }}
>>>>>>> c873058b98aeca0f257091eae6b357457ef63341
