apiVersion: v1
kind: Service
metadata:
  name: pdns-recursor-dns
  namespace: dns-dev
spec:
  selector:
    app: powerdns-recursor
  type: LoadBalancer
  ports:
  - port: 53
    targetPort: 9053
    protocol: UDP
    name: recursor-dns-udp